### ISSUE TITLE
Cleaned document text for BERTopic eval?

### ISSUE THREAD

**Issue by drob-xx** [MaartenGr/BERTopic_evaluation#4]
If I'm reading this right it looks like the corpus that is being used for the 20NewsGroups / BERTopic evaluation has been substantially trimmed. I've adjusted some code from the 'BERTopic' section in the Evaluation notebook:

```
# Prepare data
dataset, custom = "20NewsGroup", False
data_loader = DataLoader(dataset)
_, timestamps = data_loader.load_docs()
data = data_loader.load_octis(custom)
data = [" ".join(words) for words in data.get_corpus()]
```
If I understand correctly, to load the 20NewsGroup data the `dataset` and custom `variables` should be set as above.  The result of this is a substantially edited version of 20NewsGroup - it has 16,309 documents as opposed to the 18,846 in the raw 20NewsGroup, more significantly for BERTopic each document has been heavily reduced. Examples:

`data[0] == fax modem card sell mail`

`data[30] == lucky dog apply equal force early version recently author decide important mention refer request default attribute window warning read provide border default border valid window depth doesn match parent border correct depth border problem problem find make sense border implementation define conversion wire format border implementation provide type fair catch mouse
`

The topics created by this data are pretty messy and seem clearly inferior when compared to the topics created by feeding the unedited text from 20NewsGroup into BERTopic directly. 

My understanding is that we don't want to be heavily trimming BERTopic input text. Perhaps I've just misunderstood how to use the code here?

**Comment by MaartenGr** [comment]
Assuming you are using a transformer-based model, BERTopic indeed does not need preprocessed text and generally does better when using unprocessed text. This might be different though if an embedding model is used that does not, or to a lesser extent, consider context, such as TF-IDF matrices. 

In this paper, I aimed to show every side of BERTopic and making sure that every comparison was done fairly. LDA, for example, typically does better with preprocessed data. So it would be fair to show how LDA performs against BERTopic using the same input data, even though BERTopic might be at a disadvantage. Moreover, if I compared LDA with BERTopic but they have different input data, it would be comparing apples to oranges. You do not know whether any differences in performance would be due to the algorithm or due to the preprocessing steps.

**Comment by drob-xx** [comment]
Understood. I just wanted to make sure I wasn't missing something. It does seem counter-intuitive though - I understand the data consistency issue - but the two methods are very divergent in this regard and we could say that in using the processed input text we're comparing oranges to apples :).
