### ISSUE TITLE
Unicode Decode Error on local machine

### ISSUE THREAD

**Issue by bilgehanozkan** [MaartenGr/BERTopic_evaluation#6]
Hello Maarten,
I've installed this package on my local computer but getting "UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 7365: character maps to <undefined>" error at dataloader step (for all datasets).  I can run the notebooks fine on Google Colab when I install the package there. I tried encoding= "utf-8" and on_bad_line = "skip" but they didn't work either. Also I installed all packages mentioned in "setup.py" seperately  but still I can't figure out what is wrong with my system. 
I'm using anaconda on windows 10 and my python version is 3.9.
Is there an encoding configuration or something like that I'm missing? I'm a beginner at nlp and programming, so I apologies if there is an obvious solution.

Thank you.

**Comment by MaartenGr** [comment]
It might be that an earlier version of python is needed since it does work on Google Colab, which I believe supports only 3.7 but I am not entirely sure. Also, I just read a message that they are using 3.8 currently which might have changed things. This repo is merely for showcasing how the evaluation procedure is done for the BERTopic paper and is not meant to run for other datasets. If you are interested in running it for your own dataset, I would advise looking at [OCTIS](https://github.com/MIND-Lab/OCTIS) instead.

**Comment by bilgehanozkan** [comment]
Thanks for quick response, I tried a few things. It seems windows default codec (cp1252) causes the error. 
Thank you for your support and advice.
